### ISSUE TITLE
Minor improvements

### ISSUE THREAD

**Issue by bktan81** [CraftMyPDF/n8n-nodes-craftmypdf#4]
- Remove "Load Data From" field from Create Image and Create PDF
- Set default value of Version to zero

**Comment by Juneezee** [comment]
> Set default value of Version to zero.

I think the documentation for the `version` field can be further clarified. For example, the `version` field of [`POST /create`](https://craftmypdf.com/docs/index.html#tag/PDF-Generation-API/operation/create) says:

> To generate a PDF using a specific version of the template. We use the latest template version unless you specify otherwise.

On the template designer page, we can see the template versions

![image](https://github.com/user-attachments/assets/35a7f527-ff20-45a0-9197-6184f6caeba3)

As a reader I would have thought that the default value of `version` is `"latest"`, but not `"0"`.

**Comment by bktan81** [comment]
Hi @Juneezee ,
In fact, latest = 0 

I will update the UI a bit to reflect that
